import type { Product, ShopData } from "./types";

export const CATEGORIES = [
  "Drinks",
  "Groceries",
  "Cooking",
  "Cleaning",
  "Toiletries",
  "Baby",
  "Other",
];

export const EXPENSE_CATEGORIES = [
  "Transport",
  "Food",
  "Electricity",
  "Airtime/Data",
  "Repairs",
  "Household",
  "Shop",
  "School",
  "Other",
];

export const ADJUSTMENT_REASONS = [
  "Missing",
  "Damaged",
  "Expired",
  "Personal use",
  "Counting error",
  "Other",
];

export const DIFFERENCE_REASONS = [
  "Unrecorded sale",
  "Expense not recorded",
  "Wrong change",
  "Cash counting error",
  "Money taken from cash",
  "Other",
];

const p = (
  name: string,
  category: string,
  buyPrice: number,
  sellPrice: number,
  stock: number,
  minStock = 5,
): Product => ({
  id: name.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
  name,
  category,
  buyPrice,
  sellPrice,
  stock,
  minStock,
});

export const SAMPLE_PRODUCTS: Product[] = [
  p("Spurds Small", "Groceries", 0.5, 0.5, 10),
  p("Captain Drink", "Drinks", 0.5, 0.5, 11),
  p("Kambucha Drink", "Drinks", 1, 1, 8),
  p("Switch", "Drinks", 1, 1, 5),
  p("U-Fresh Maheu Big", "Drinks", 0.5, 0.5, 4),
  p("Stella Masamba", "Groceries", 0.5, 0.5, 7),
  p("Willards Chips", "Groceries", 0.5, 0.5, 4),
  p("Steri Milk", "Groceries", 1, 1, 9),
  p("Munchies Biscuits", "Groceries", 0.5, 0.5, 4),
  p("Yummy Biscuits", "Groceries", 0.5, 0.5, 22),
  p("Zimgold Cooking Oil", "Cooking", 3.75, 3.75, 14),
  p("Olivine Cooking Oil", "Cooking", 3.5, 3.5, 7),
  p("Puredrop Cooking Oil", "Cooking", 3.65, 3.65, 7),
  p("Bigburn Sope", "Toiletries", 1.5, 1.5, 11),
  p("Glicyline Aloe Vera", "Toiletries", 1, 1, 2),
  p("Bermuda Biscuits", "Groceries", 0.5, 0.5, 11),
  p("Mazoe Drink", "Drinks", 3.95, 3.95, 3),
  p("Mazoe Raspberry", "Drinks", 3, 3, 3),
  p("BOOM Pest", "Cleaning", 0.5, 0.5, 16),
  p("Vaseline Small", "Toiletries", 1, 1, 10),
  p("Hi-Life", "Toiletries", 0.5, 0.5, 22),
  p("Sona", "Toiletries", 0.6, 0.6, 7),
  p("Jade", "Toiletries", 1, 1, 2),
  p("Revive Big", "Drinks", 1, 1, 6),
  p("Dragon Energy Drink", "Drinks", 1, 1, 1),
  p("Revive Maheu Big", "Drinks", 1, 1, 10),
  p("Frutta Drink", "Drinks", 1, 1, 3),
  p("Revive Small", "Drinks", 0.5, 0.5, 32),
  p("Swissup Drink 5L", "Drinks", 2, 2, 1),
  p("Coated Biscuits", "Groceries", 1.6, 1.6, 10),
  p("Sparkle", "Drinks", 1, 1, 27),
  p("2L Coke", "Drinks", 2, 2, 14),
  p("Aloha 2KG", "Cleaning", 5, 5, 8),
  p("Aloha 1KG", "Cleaning", 2.5, 2.5, 10),
  p("MAQ 2KG", "Cleaning", 5.5, 5.5, 8),
  p("BOOM 1KG", "Cleaning", 2.5, 2.5, 9),
  p("Water 2L", "Drinks", 0.5, 0.5, 6),
  p("Gold Milk Small", "Groceries", 0.5, 0.5, 15),
  p("Celerac Small", "Baby", 2.5, 2.5, 1),
  p("Petty Coke", "Drinks", 0.5, 0.5, 12),
  p("Water 500ML", "Drinks", 0.25, 0.25, 0),
  p("Matches", "Other", 0.25, 0.25, 10),
  p("Softcare Small", "Cleaning", 1, 1, 8),
  p("Cute Pumper", "Baby", 1, 1, 5),
  p("Pumper", "Baby", 5, 5, 9),
  p("Swissup Drink 2L", "Drinks", 1, 1, 7),
  p("Sunsoya Cooking Oil", "Cooking", 3.25, 3.25, 2),
  p("Raha Cooking Oil", "Cooking", 3.5, 3.5, 4),
  p("Merinda", "Drinks", 0.5, 0.5, 24),
  p("Eversharp", "Other", 0.25, 0.25, 49),
  p("Casacade", "Drinks", 0.5, 0.5, 40),
  p("BOOM 500G", "Cleaning", 1.5, 1.5, 17),
  p("BOOM 2KG", "Cleaning", 5, 5, 5),
  p("Rice 5KG Martina", "Groceries", 5.5, 5.5, 2),
  p("Charhorn", "Other", 1.5, 1.5, 13),
  p("Rice 5KG Raha", "Groceries", 5.5, 5.5, 1),
  p("Rice 5KG Mr Rice", "Groceries", 5.5, 5.5, 1),
  p("Macaroni 500G", "Groceries", 0.5, 0.5, 8),
  p("Quickbrew", "Groceries", 1, 1, 1),
  p("Tomato Sauce", "Groceries", 1, 1, 3),
  p("Rabroy Salad", "Groceries", 1.5, 1.5, 7),
  p("Olivia Beans", "Groceries", 1, 1, 4),
  p("Dovi", "Groceries", 1, 1, 13),
  p("Jam", "Groceries", 1.6, 1.6, 5),
  p("Mr Rice 2KG", "Groceries", 2, 2, 11),
  p("Raha Rice 2KG", "Groceries", 2, 2, 5),
  p("Idea Rice 2KG", "Groceries", 2, 2, 7),
  p("Spaghetti", "Groceries", 0.5, 0.5, 5),
  p("Noodles", "Groceries", 1.75, 1.75, 6),
  p("Martina Rice 1KG", "Groceries", 1, 1, 6),
  p("Hulletts Sugar 2KG", "Groceries", 3, 3, 6),
  p("Tapi Tapi Sugar", "Groceries", 2.75, 2.75, 10),
  p("Salt Red Seal", "Groceries", 0.5, 0.5, 3),
  p("Salt Godo", "Groceries", 0.5, 0.5, 1),
  p("Popcorn", "Groceries", 1, 1, 4),
  p("Cerevita", "Groceries", 3, 3, 3),
  p("Cerelac Big", "Baby", 4.8, 4.8, 4),
  p("Cerelac Small", "Baby", 2.5, 2.5, 4),
  p("Ellis Brown Milk Half", "Groceries", 1.8, 1.8, 0),
  p("Ellis Brown Box", "Groceries", 3.6, 3.6, 0),
  p("Flour", "Groceries", 2, 2, 11),
  p("Salad Mayonnaise", "Groceries", 3, 3, 2),
  p("Vinegar", "Groceries", 1, 1, 4),
  p("Dlite 350ML", "Drinks", 1, 1, 8),
  p("Lemon Biscuits", "Groceries", 0.5, 0.5, 0),
  p("Maputi", "Groceries", 1, 1, 6),
  p("Yogurt", "Groceries", 0.5, 0.5, 0),
  p("Buttermilk Maheu", "Drinks", 0.6, 0.6, 6),
  p("Milkit", "Groceries", 0.5, 0.5, 2),
  p("Revive Maheu Small", "Drinks", 0.25, 0.25, 0),
  p("U-Fresh", "Drinks", 0.25, 0.25, 4),
  p("Wildcat", "Drinks", 0.5, 0.5, 11),
  p("Pepsi", "Drinks", 0.5, 0.5, 0),
  p("Polony", "Groceries", 0.5, 0.5, 0),
  p("Lacto", "Groceries", 1, 1, 0),
  p("Fizzi Drink", "Drinks", 0.5, 0.5, 0),
  p("Water 5L", "Drinks", 1, 1, 2),
  p("Hupfu 10KG", "Groceries", 5, 5, 2),
  p("Eggs (6)", "Groceries", 1, 1, 75),
  p("Lifeboy", "Toiletries", 1, 1, 3),
  p("Lux Soap", "Toiletries", 1, 1, 6),
  p("Closeup", "Toiletries", 1, 1, 4),
  p("Colgate", "Toiletries", 1, 1, 4),
  p("Superblack", "Toiletries", 1, 1, 6),
  p("Clear", "Toiletries", 1, 1, 4),
  p("Baby Crazy", "Baby", 2, 2, 3),
  p("Imgrams", "Toiletries", 3, 3, 3),
  p("Vaseline Blueseal", "Toiletries", 3, 3, 4),
  p("Kiwi", "Cleaning", 1, 1, 7),
  p("Rajah", "Groceries", 1, 1, 8),
  p("Soya Chunks", "Groceries", 0.5, 0.5, 8),
  p("Royco", "Groceries", 0.5, 0.5, 10),
  p("Binto", "Groceries", 0.5, 0.5, 8),
  p("Spice", "Groceries", 0.5, 0.5, 6),
  p("Lighter", "Other", 0.5, 0.5, 15),
  p("Angel Tissue", "Groceries", 0.5, 0.5, 18),
  p("Flame Cigaret (20)", "Other", 0.5, 0.5, 0),
  p("Mint Cigaret (20)", "Other", 0.5, 0.5, 0),
  p("Pacific Storm Cigaret (20)", "Other", 1, 1, 0),
  p("Breeze Cigaret (20)", "Other", 1, 1, 0),
  p("Everest Cigaret (20)", "Other", 1.5, 1.5, 0),
];

export const QUICK_SALE_NAMES = [
  "2L Coke",
  "Mazoe Drink",
  "Mr Rice 2KG",
  "Sunsoya Cooking Oil",
  "Revive Small",
  "Noodles",
];

export const initialData = (): ShopData => ({
  products: SAMPLE_PRODUCTS,
  sales: [],
  expenses: [],
  purchases: [],
  adjustments: [],
  closings: [],
  settings: { shopName: "Nosha Shop", currency: "$", lowStockDefault: 5 },
});

export const DEFAULT_CATEGORY = "Groceries";
export const DEFAULT_EXPENSE_CATEGORY = "Shop";
export const DEFAULT_DIFFERENCE_REASON = "Unrecorded sale";
export const DEFAULT_ADJUSTMENT_REASON = "Counting error";
